loki:
  memberlist:
    abort_if_cluster_join_fails: false
  limits_config:
    reject_old_samples: false
  config:
    schema_config:
      configs:
        - from: 2022-10-28
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            prefix: loki_
            period: 24h
    storage_config:
      aws:
        s3: s3://us-east-1/bluelightco-loki
        access_key_id: <AWS_ACCESS_KEY_ID> 
        secret_access_key: <AWS_SECRET_ACCESS_KEY>
        s3forcepathstyle: true
        bucketnames: bluelightco-loki
        region: us-east-1
        insecure: false
        sse_encryption: false
        http_config:
          idle_conn_timeout: 90s
          response_header_timeout: 0s
          insecure_skip_verify: false
    compactor:
      working_directory: /data/compactor
      shared_store: s3
      compaction_interval: 5m
    auth_enabled: true
    chunk_store_config:
      max_look_back_period: 0s
